// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0SZMmotMNTV0iwgrtnptATd9JtzDmYs',
    appId: '1:539615363537:web:f2f60d6bfb9b834225e0f0',
    messagingSenderId: '539615363537',
    projectId: 'app-pos-project',
    authDomain: 'app-pos-project.firebaseapp.com',
    storageBucket: 'app-pos-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy7q5ZwK9fIP3k2ZdDFtUUaHXYcWRAF9c',
    appId: '1:539615363537:android:b003c9565dee43ad25e0f0',
    messagingSenderId: '539615363537',
    projectId: 'app-pos-project',
    storageBucket: 'app-pos-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeQ7vC9rQLuUdRFc-BsT4TsVBane4r39c',
    appId: '1:539615363537:ios:0910b09de3fc817c25e0f0',
    messagingSenderId: '539615363537',
    projectId: 'app-pos-project',
    storageBucket: 'app-pos-project.appspot.com',
    iosBundleId: 'com.example.finalProjectApplicationPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeQ7vC9rQLuUdRFc-BsT4TsVBane4r39c',
    appId: '1:539615363537:ios:0910b09de3fc817c25e0f0',
    messagingSenderId: '539615363537',
    projectId: 'app-pos-project',
    storageBucket: 'app-pos-project.appspot.com',
    iosBundleId: 'com.example.finalProjectApplicationPos',
  );
}
